//Login actions
export const SET_LOGIN_FORM = 'SET_LOGIN_FORM'
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
export const SET_USER_DATA = 'SET_USER_DATA'
//Register actions
export const REGISTER_NEXT_STEP = 'REGISTER_NEXT_STEP'
export const REGISTER_PREV_STEP = 'REGISTER_PREV_STEP'
export const SET_REGISTER_VALIDATION = 'SET_REGISTER_VALIDATION'
export const REGISTER_RESET_STEPS = 'REGISTER_RESET_STEPS'
export const SET_REGISTER_FIELD = 'SET_REGISTER_FIELD'
export const SET_BASIC_FIELD = 'SET_BASIC_FIELD'
//Recovery actions
export const SET_RECOVERY_ERROR = 'SET_RECOVERY_ERROR'
export const SET_RECOVERY_REQUEST = 'SET_RECOVERY_REQUEST'
// Camera && pictures
export const SET_REGISTER_PHOTO = 'SET_REGISTER_PHOTO'
export const SET_REGISTER_SELFIE = 'SET_REGISTER_SELFIE'
// RequestWizards
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_SUB_CATEGORY = 'SET_SUB_CATEGORY'
export const SET_SERVICES = 'SET_SERVICES'
export const SET_ADDRESS_FIELD = 'SET_ADDRESS_FIELD'
export const SET_REQUEST_DESCRIPTION = 'SET_REQUEST_DESCRIPTION'
export const FETCH_REQUESTS = 'FETCH_REQUESTS'
export const FETCH_CONFIRMED_REQUESTS = 'FETCH_CONFIRMED_REQUESTS'
export const SET_REQUEST = 'SET_REQUEST'

